# Generated by Django 4.0 on 2021-12-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='last',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
